name: Publish to Docker Hub

on:
  push:
    branches:
      - master
    paths:
      - 'Dockerfile.latest'
      - 'cronjob'

jobs:
  publish-to-docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          BRANCH=$(git rev-parse --abbrev-ref HEAD)
          echo "BRANCH: ${BRANCH}"
          DOCKER_TAGS="${BRANCH},latest"
          echo "DOCKER_TAGS=${DOCKER_TAGS}" >> $GITHUB_ENV

      - name: Publish Docker Github Action
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: joppes/resourcespace
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile.latest
          tags: ${{ env.DOCKER_TAGS }}
